wallpaper {
    monitor = HDMI-A-1  # Or empty for all/fallback
    path = /E/linux/wallpapers/a_woman_sitting_on_a_couch_looking_out_a_window.png
    #fit_mode = cover # cover, contain, tile, fill
}

wallpaper {
    monitor = HDMI-A-2  # Or empty for all/fallback
    path = /E/linux/wallpapers/a_room_with_a_desk_and_a_chair_and_a_skull_on_the_wall.jpg
    #fit_mode = cover # cover, contain, tile, fill
}

#enable splash text rendering over the wallpaper
#splash = true

#fully disable ipc
# ipc = off

